Homework8/force-app/main/default/objects/logger_framework__e/logger_framework__e.object-meta.xml
<CustomObject>
    <label>logger framework</label>
    <pluralLabel>logger frameworks</pluralLabel>
</CustomObject>

Homework8/force-app/main/default/objects/logger_framework__e/fields/payload__c.field-meta.xml
<CustomField>
    <fullName>payload__c</fullName>
    <label>payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Homework8/force-app/main/default/objects/Vacancy__c/Vacancy__c.object-meta.xml
<CustomObject>
    <label>Vacancy</label>
    <nameField>
        <label>Vacancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Homework8/force-app/main/default/objects/Vacancy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Homework8/force-app/main/default/classes/VacancyBatch.cls
/**
 * Created by OlexandrKrykun on 04.04.2021.
 */

public with sharing class VacancyBatch implements Database.Batchable<SObject> {
  private String batchQuery;
  private String standardQuery = 'Select id from Vacancy__c where status__c = \'closed\' ';

  public VacancyBatch(String query) {
    this.batchQuery = query; 
  }
  public VacancyBatch() {
    this.batchQuery = standardQuery;
  }

  public Database.QueryLocator start(Database.BatchableContext context) {
    return Database.getQueryLocator(this.batchQuery);
  }
  public void execute(
    Database.BatchableContext context,
    List<Vacancy__c> vacancies
  ) {
      List<CronTrigger> CronTrigger = [
              SELECT
                      CreatedById,
                      CreatedDate,
                      CronExpression,
                      CronJobDetail.Name,
                      CronJobDetail.JobType,
                      EndTime,
                      Id,
                      LastModifiedById,
                      NextFireTime,
                      OwnerId,
                      PreviousFireTime,
                      StartTime,
                      State,
                      TimesTriggered,
                      TimeZoneSidKey
              FROM CronTrigger
      ];
      List<AsyncApexJob> apexJobs = [
              SELECT
                      ApexClassId,
                      CompletedDate,
                      CreatedById,
                      CreatedDate,
                      ExtendedStatus,
                      Id,
                      JobItemsProcessed,
                      JobType,
                      LastProcessed,
                      LastProcessedOffset,
                      MethodName,
                      NumberOfErrors,
                      ParentJobId,
                      Status,
                      TotalJobItems
              FROM AsyncApexJob];
      for(CronTrigger cron:CronTrigger){
        System.debug('CronTriggerName->'+ cron.CronJobDetail.Name);
        System.debug('CronTriggerJobType->'+ cron.CronJobDetail.JobType);
      }
      for(AsyncApexJob j:apexJobs){
        System.debug('AsyncApexJob->'+j);
      }
      try{
        delete vacancies;

        Map<String,Object> eventPayloadMap = new Map<String,Object>();
        eventPayloadMap.put('Message','Batch finished successfully: batch ID ' + context.getJobId());
        eventPayloadMap.put('LogLevel','INFO');

        String eventPayload = JSON.serialize(eventPayloadMap);
        logger_framework__e logEvent = new logger_framework__e(payload__c=eventPayload);
        Database.SaveResult sr = EventBus.publish(logEvent);
        if (sr.isSuccess()) {
            System.debug('Successfully published event.');
        } else {
          System.debug('Event publish failed.');
        }

      } catch(Exception ex){

        Map<String,Object> eventPayloadMap = new Map<String,Object>();
        eventPayloadMap.put('Exception',ex);
        eventPayloadMap.put('Context',context);
        eventPayloadMap.put('LogLevel','Error');

        String eventPayload = JSON.serialize(eventPayloadMap);
        logger_framework__e logEvent = new logger_framework__e(payload__c=eventPayload);
        Database.SaveResult sr = EventBus.publish(logEvent);
        if (sr.isSuccess()) {
            System.debug('Successfully published event.');
        } else {
          System.debug('Event publish failed.');
        }

        throw ex;
      }
    }
  
  public void finish(Database.BatchableContext context) {
  }



  public class customException extends Exception{}
}