Homework8/force-app/main/default/objects/Log__c/fields/Context_Id__c.field-meta.xml
<CustomField>
    <fullName>Context_Id__c</fullName>
    <label>Context_Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Homework8/force-app/main/default/objects/Log__c/fields/Context_Name__c.field-meta.xml
<CustomField>
    <fullName>Context_Name__c</fullName>
    <label>Context_Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Homework8/force-app/main/default/objects/Log__c/fields/Logging_lavel__c.field-meta.xml
<CustomField>
    <fullName>Logging_lavel__c</fullName>
    <label>Logging_lavel</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Homework8/force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Exception description</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Homework8/force-app/main/default/objects/Log__c/fields/Stack_trace_String__c.field-meta.xml
<CustomField>
    <fullName>Stack_trace_String__c</fullName>
    <description>Exception Stack trace</description>
    <label>Stack trace String</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Homework8/force-app/main/default/classes/Logger.cls
public with sharing class Logger {
    public static void Log(String logLevel,String Message) {
        Log__c logRecord = new Log__c();
        logRecord.Logging_lavel__c = logLevel;
        logRecord.Message__c = Message;
        insert logRecord;
    }
    public static void Log(Database.BatchableContext context, Exception ex, String logLevel) {
        Log__c logRecord = new Log__c();
        logRecord.Context_Id__c = context.getJobId();
        List<CronJobDetail> v1 = [SELECT Name from CronJobDetail where Id = :context.getJobId() limit 1];
        logRecord.Context_Name__c = v1[0].Name;
        logRecord.Message__c = ex.getMessage();
        logRecord.Stack_trace_String__c = ex.getStackTraceString();
        logRecord.Logging_lavel__c = logLevel;
        insert logRecord;
    }
}